name: certbot-cron
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '15 4 * * 3'
env:
  github_sha: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
            fetch-depth: 1
      - name: Set environment variables
        run: | 
            echo '::set-env name=TERM::xterm'
      - name: Pull in docker image
        run: |
            source .env
            echo ' - pull in my docker images as helpers'
            docker login docker.pkg.github.com --username ${REPO_OWNER} --password ${{ secrets.github_token }} &>/dev/null
            docker pull ${PROXY_DOCKER_IMAGE}
      - name: Setup Gcloud
        uses: googlecloudplatform/github-actions/setup-gcloud@master
        with:
            version: "270.0.0"
            service_account_email: ${{ secrets.client_email }}
            service_account_key: ${{ secrets.gce_key }}
      - name: Configure GCE project
        run: |
            source .env
            gcloud config set project ${GCE_PROJECT}
            gcloud config set compute/zone ${GCE_ZONE}
            # gcloud compute instances list
            gcloud compute config-ssh &>/dev/null
            gcloud compute ssh ${GCE_NAME} --command \
            "docker login docker.pkg.github.com --username ${REPO_OWNER} --password ${{ secrets.github_token }}"
            gcloud compute ssh ${GCE_NAME} --command "docker pull ${PROXY_DOCKER_IMAGE}"
            #gcloud info
      - name: Renew Certs Every Week On Wednesday  
        run: |
            source .env
            pushd gcloud
            make -f certbot.mk renew
            popd

