name: CI

on:
  push:
    branches: master
# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  GCE_PROJECT: ${{ secrets.PROJECT_ID }}
  GCE_ZONE: australia-southeast1-b
  GCE_NAME: gmack

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_email: ${{ secrets.CLIENT_EMAIL }}
          service_account_key: ${{ secrets.GCE_KEY }}
      - name: gcloud configure
        run: |
          gcloud config set project ${GCE_PROJECT}
          gcloud compute instances list
          # gcloud compute config-ssh
      - name: gcloud ssh
        run: |
          echo '-------------------------------'
          #echo ${HOST}
          gcloud compute ssh ${GCE_NAME} --zone ${GCE_ZONE} --container or --command 'ls -al .'
          # gcloud info
          echo '-------------------------------'
          # echo -n 'project: '
          # gcloud config get-value project
          # echo -n 'zone: '
          # gcloud config get-value compute/zone
          # echo;echo -n 'region: '
          # gcloud config get-value compute/region
          # echo;echo -n 'zone: '
          # gcloud config get-value compute/zone
          # echo '-------------------------------'
          # gcloud compute ssh gmack --container or --command 'ls -al /etc/letsencrypt/live'
