name: CI

on:
  push:
    branches: master
# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_email: ${{ secrets.CLIENT_EMAIL }}
          service_account_key: ${{ secrets.GCE_KEY }}
      - name: gcloud info
        run: |
            #gcloud info
            #gcloud iam service-accounts list
            # gcloud config set account grantmacken@gmail.com
            # gcloud auth list
            gcloud config get-value project
            gcloud config set project gmack-200121
            gcloud config get-value project
            # gcloud projects list
            # gcloud compute config-ssh --dry-run
            # gcloud compute ssh gmack --container or --command 'ls -al /etc/letsencrypt/live'
