name: CI

on:
  push:
    branches: master
# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  EMAIL: ${{ secrets.GCP_SA_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  IMAGE: gke-test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCE_KEY }}
      - name: gcloud info
        run: gcloud info
