name: CI

on:
  push:
    branches: master
# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      # - name: Debug
      #   uses: hmarr/debug-action@master
      #
      - name: Install Dependencies
        run: |
            pip install --upgrade pip setuptools wheel
            pip install scour
      # - name: Pull images
      #   run: |
      #     source .env
      #     docker pull ${XQERL_DOCKER_IMAGE}
      #     echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     docker pull ${PROXY_DOCKER_IMAGE}
      # - name: Setup gcloud
      #   uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      #   with:
      #     version: "270.0.0"
      #     service_account_email: ${{ secrets.CLIENT_EMAIL }}
      #     service_account_key: ${{ secrets.GCE_KEY }}
      # - name: gcloud configure
      #   run: |
      #     source .env
      #     gcloud config set project ${GCE_PROJECT}
      #     gcloud config set compute/zone ${GCE_ZONE}
      #     # gcloud compute instances list
      #     gcloud compute config-ssh &>/dev/null
      # # - name: gcloud info
      # #   run: gcloud info
      # - name: set up certs and hosts file
      #   run: |
      #     pushd proxy
      #     make certsToHost
      #     popd
      # - name: bring containers up
      #   run: |
      #       make up
      #       docker ps
      # - name: build the xqerl web app
      #   run: |
      #       source .env
      #       # move to domain
      #       pushd site/${DOMAIN}
      #       # compile xQuery libs
      #       # compile order is defined in the  site/[DOMAIN] Makefile 
      #       # NOTE! order in important as some libs depend on others
      #       make app
      #       popd
      # - name: take containers down
      #   run: |
      #       make down


